// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwmlhbfpsubyrbwzdxjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3bWxoYmZwc3VieXJid3pkeGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MzkxMDIsImV4cCI6MjA3ODIxNTEwMn0.GI59Hqxg5OuQmTGIfklimOfgJAcXg2OtwLG7LRIw6Ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});