// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfsbmovzezhhekqukljn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmc2Jtb3Z6ZXpoaGVrcXVrbGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MTYxNDQsImV4cCI6MjA3ODM5MjE0NH0.DTinmVOoDtNuq8YSDFPfS2rslZXD3ZXeBex7-GvmIw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});